### ISSUE TITLE
[FEAT] 게시판 기능 구현

### ISSUE THREAD

**Issue by jh2ee** [LikeLion11th-SY-Team/nong-min#9]
## 💡 Issue

게시판 뷰 구현
- 게시글 미리보기 뷰 구현
- 게시글 카드 구현
- 게시글 작성 뷰 구현
    - 게시판 선택, 제목, 내용, 이미지 첨부 기능
    - 데이터 백엔드 전달
게시글 상세 뷰 구현
- 게시글 데이터 랜더링
- 게시글 수정 및 삭제
- 좋아요 기능
- 댓글 작성 및 삭제 (수정x)

## 📝  todo
- [ ] todo !
- [x] 게시글 미리보기 뷰 구현
- [ ] 게시글 카드 구현
- [ ] 게시글 작성 뷰 구현
    - [ ] 게시판 선택, 제목, 내용, 이미지 첨부 기능
    - [ ] 데이터 백엔드 전달
- [ ] 게시글 상세 뷰 구현
    - [x] 게시글 데이터 랜더링
    - [ ] 게시글 수정 및 삭제
    - [x] 좋아요 기능
    - [ ] 댓글 작성 및 삭제 (수정x)

## 📸 Screenshot

<img width="827" alt="image" src="https://github.com/LikeLion11th-SY-Team/nong-min/assets/121475533/1bb5665e-42ec-422f-9063-87b006d37de6">
<img width="366" alt="image" src="https://github.com/LikeLion11th-SY-Team/nong-min/assets/121475533/92dbdd3d-41cf-42d2-92fb-48edbd075539">
